// const DEFAULT_COMMISSION = 0.001;
const DEFAULT_COMMISSION = 0;

const MIN_PAYOUT_AMOUNT = 0.001;

const SPL_TOKEN_SEND_TRANSACTION_STATUS = {
  UNKNOWN: -1,
  PENDING: 0,
  FAILED: 1,
  SUCCESS: 2,
  MISMATCH: 3,
};

const BET_REWARD_TYPE = {
  NFT: 0,
  TOKEN: 1,
  TOKEN_2022: 2,
  SOL: 3,
};

module.exports = {
  DEFAULT_COMMISSION,
  SPL_TOKEN_SEND_TRANSACTION_STATUS,
  BET_REWARD_TYPE,
  MIN_PAYOUT_AMOUNT,
};
