const BLOCKCHAIN_NETWORK = {
  SOLANA: 1,
  POLYGON: 2,
};

const SPL_TOKEN_SEND_TRANSACTION_TYPE = {
  SOLANA: 0,
  SPL_TOKEN: 1,
  SPL_TOKEN_2022: 2,
};

const SPL_TOKEN_SEND_TX_STATUS = {
  PENDING: 0,
  FAILED: 1,
  SUCCESS: 2,
  MISMATCHED: 3,
};

const SPL_TOKEN_ADDRESS = {
  SOLANA: "So11111111111111111111111111111111111111112",
  USDC: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
};

const TOKEN_TYPE = {
  SOLANA: 0,
  SPL_TOKEN: 1,
  SPL_TOKEN_2022: 2,
  USDC: 3,
};

const RAFFLE_STATUS = {
  DRAFT: 0,
  UPCOMING: 1,
  LIVE: 2,
  ENDED: 3,
  CANCELLED: 4,
  SUSPENDED: 5,
  DELETED: 6,
  REFUNDED: 7,
};

const RAFFLE_FEATURED_STATUS = {
  FEATURED: 1,
  NOT_FEATURED: 0,
};

const RAFFLE_REWARD_TYPES = {
  NFT: 0,
  SPL_TOKEN: 1,
  SPL_TOKEN_2022: 2,
  SOLANA: 3,
};

const RAFFLE_FEATURED_POSITION = {
  FIRST: 1,
  SECOND: 2,
  THIRD: 3,
  FOURTH: 4,
  FIFTH: 5,
};

const COMMISSION_RATES = {
  HOLDER: 0.025, // 2.5% for NFT holders
  NON_HOLDER: 0.05, // 5% for non-holders
};

const TICKET_RESERVATION_STATUS = {
  RESERVED: 1,
  CONFIRMED: 2,
  EXPIRED: 3,
  CANCELLED: 4,
};

const COLLECTION_ISVERIFIED = {
  TRUE: 1,
  FALSE: 0,
};

const XP_SOURCE_TYPES = {
  TICKET_PURCHASE: "ticket_purchase",
  RAFFLE_REVENUE: "raffle_revenue",
  RAFFLE_CREATION: "raffle_creation",
};

const XP_CONFIG_KEYS = {
  TICKET_PURCHASE_RATE: "ticket_purchase_rate",
  RAFFLE_REVENUE_RATE: "raffle_revenue_rate",
  RAFFLE_CREATION_REWARD: "raffle_creation_reward",
};

function mapEnumValue(enumObj, value) {
  return Object.keys(enumObj).find((key) => enumObj[key] === value) || value;
}

module.exports = {
  BLOCKCHAIN_NETWORK,
  SPL_TOKEN_SEND_TRANSACTION_TYPE,
  TOKEN_TYPE,
  RAFFLE_STATUS,
  RAFFLE_FEATURED_STATUS,
  RAFFLE_FEATURED_POSITION,
  RAFFLE_REWARD_TYPES,
  SPL_TOKEN_ADDRESS,
  SPL_TOKEN_SEND_TX_STATUS,
  COMMISSION_RATES,
  TICKET_RESERVATION_STATUS,
  COLLECTION_ISVERIFIED,
  XP_SOURCE_TYPES,
  XP_CONFIG_KEYS,
  mapEnumValue,
};
