import type { RaffleCardProps } from "../views/home/RaffleCard";

// Export the data array
export const raffleData: RaffleCardProps[] = [
  {
    id: 1,
    image: "/assets/card1.jpg",
    title: "Legendary Fox Founder Pass",
    price: "0.5",
    sold: 78,
    total: 100,
    endTime: "2d 5h",
    tokenType: "SOL",
    isVerified: true,
    isFeatured: true,
  },
  {
    id: 2,
    image: "/assets/card2.jpg",
    title: "5000 USDC Grand Prize",
    price: "10",
    sold: 342,
    total: 500,
    endTime: "1d 12h",
    tokenType: "USDC",
    isVerified: true,
    isFeatured: false,
  },
  {
    id: 3,
    image: "/assets/card3.jpg",
    title: "Rare Solana NFT Bundle",
    price: "0.25",
    sold: 145,
    total: 200,
    endTime: "3d 8h",
    tokenType: "SOL",
    isVerified: false,
    isFeatured: false,
  },
  {
    id: 4,
    image: "/assets/card4.jpg",
    title: "Premium Hardware Wallet",
    price: "5",
    sold: 89,
    total: 150,
    endTime: "4d 2h",
    tokenType: "USDC",
    isVerified: true,
    isFeatured: false,
  },
  {
    id: 5,
    image: "/assets/card5.jpg",
    title: "Fox Club Merchandise Pack",
    price: "0.1",
    sold: 256,
    total: 300,
    endTime: "12h",
    tokenType: "SOL",
    isVerified: false,
    isFeatured: false,
  },
  {
    id: 6,
    image: "/assets/card6.jpg",
    title: "1000 BONK Token Airdrop",
    price: "1000",
    sold: 678,
    total: 1000,
    endTime: "5d",
    tokenType: "BONK",
    isVerified: true,
    isFeatured: false,
  },
];
