export const topHosts = [
  {
    rank: 1,
    wallet: "FoxK...7mQp",
    revenue: 245.8,
    raffles: 24,
    reputation: 99,
    badge: "crown",
  },
  {
    rank: 2,
    wallet: "SolM...3kPx",
    revenue: 189.5,
    raffles: 18,
    reputation: 97,
    badge: "gold",
  },
  {
    rank: 3,
    wallet: "Web3...8nRt",
    revenue: 156.3,
    raffles: 15,
    reputation: 98,
    badge: "silver",
  },
  {
    rank: 4,
    wallet: "Raff...2hKm",
    revenue: 134.7,
    raffles: 12,
    reputation: 96,
  },
  {
    rank: 5,
    wallet: "Nfts...5pLw",
    revenue: 128.9,
    raffles: 14,
    reputation: 95,
  },
  {
    rank: 6,
    wallet: "Cryp...1vXy",
    revenue: 112.4,
    raffles: 11,
    reputation: 97,
  },
  {
    rank: 7,
    wallet: "Meta...9qZn",
    revenue: 98.6,
    raffles: 9,
    reputation: 94,
  },
  {
    rank: 8,
    wallet: "Dapp...4bCs",
    revenue: 87.2,
    raffles: 8,
    reputation: 96,
  },
];

export const topBuyers = [
  {
    rank: 1,
    wallet: "Mega...5wPl",
    spent: 312.5,
    tickets: 634,
    wins: 8,
    badge: "crown",
  },
  {
    rank: 2,
    wallet: "Luck...9mKx",
    spent: 267.8,
    tickets: 542,
    wins: 6,
    badge: "gold",
  },
  {
    rank: 3,
    wallet: "Rafi...3nQp",
    spent: 234.2,
    tickets: 478,
    wins: 5,
    badge: "silver",
  },
  {
    rank: 4,
    wallet: "Dege...7hRt",
    spent: 198.6,
    tickets: 412,
    wins: 4,
  },
  {
    rank: 5,
    wallet: "Play...2kMn",
    spent: 176.4,
    tickets: 367,
    wins: 3,
  },
  {
    rank: 6,
    wallet: "Gamb...8pLw",
    spent: 154.3,
    tickets: 321,
    wins: 4,
  },
  {
    rank: 7,
    wallet: "Trad...1vXz",
    spent: 142.1,
    tickets: 298,
    wins: 2,
  },
  {
    rank: 8,
    wallet: "Hold...6qZm",
    spent: 128.9,
    tickets: 267,
    wins: 3,
  },
];
